version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:lts  # Using Node.js image with LTS version for both building and deploying
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build the Application
          command: npm run build
      - run:
          name: Install Firebase CLI
          command: curl -sL https://firebase.tools | bash
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
